baseURL = 'https://integracao-passo-a-passo.github.io/ebook/'
languageCode = 'pt-BR'
title = 'Camel Passo a Passo'
themesDir = "themes"
# https://hugothemesfree.com/declination-of-matcornic-learn-theme-to-hugo/
theme = "docdock"