baseURL = 'https://www.angusyoung.org/camel-passo-a-passo/'
languageCode = 'pt-BR'
title = 'Camel Passo a Passo'
themesDir = "themes"
# https://hugothemesfree.com/declination-of-matcornic-learn-theme-to-hugo/
theme = "docdock"